-- V12 - M6 (Cadastro & Visual): catalogo de cores + atributos botanicos do produto.
-- ADITIVA e NAO destrutiva (P12): nenhuma coluna existente e alterada/removida; tudo novo nasce NULL
-- ou vazio. O catalogo atual de produtos continua valido sem backfill.

-- ---- (1) Catalogo de cores (T-M6-01) ----------------------------------------------------------
CREATE TABLE cor (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- SEMPRE no formato CANONICO (AD-SQ-90): MAIUSCULO, sem espacos, espaco interno vira hifen.
    -- Ex.: 'AZUL', 'VERMELHO', 'CINZA-ESCURO'. Nao existe "nome de exibicao" separado.
    nome          VARCHAR(40)  NOT NULL,
    hex           VARCHAR(7),                       -- amostra opcional '#RRGGBB' (AD-SQ-81)
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_cor_hex CHECK (hex IS NULL OR hex ~ '^#[0-9A-Fa-f]{6}$'),
    -- Unicidade sobre o valor CANONICO. Como 'Azul', 'azul' e ' AZUL ' convergem para 'AZUL' ANTES
    -- do insert, um UNIQUE simples ja garante a regra do dono ("nao pode criar Azul se existe AZUL").
    CONSTRAINT uk_cor_nome UNIQUE (nome),
    -- Defesa em profundidade: o banco recusa qualquer nome fora da forma canonica.
    -- regex = 1+ blocos sem espaco/hifen separados por UM hifen -> sem hifen nas pontas, sem hifen
    -- duplo, sem espaco em lugar nenhum. `char_length >= 2` espelha o tamanho minimo do servico.
    CONSTRAINT ck_cor_nome_canonico CHECK (
        nome = upper(nome)
        AND nome ~ '^[^[:space:]-]+(-[^[:space:]-]+)*$'
        AND char_length(nome) >= 2
    )
);
-- NAO existe `ux_cor_nome_lower` (indice funcional sobre lower(nome)): com o persistido ja canonico,
-- `lower(nome)` seria redundante - dois canonicos nunca diferem so por caixa. Ver AD-SQ-90.

-- ---- (2) N:N produto <-> cor -------------------------------------------------------------------
-- RESTRICT no lado da cor = defesa em profundidade da P3 (o servico ja devolve 409 antes de tentar).
-- CASCADE no lado do produto = hard delete de produto limpa o vinculo (FC-08), igual a evento_produto.
CREATE TABLE produto_cor (
    produto_id BIGINT NOT NULL,
    cor_id     BIGINT NOT NULL,
    CONSTRAINT pk_produto_cor PRIMARY KEY (produto_id, cor_id),
    CONSTRAINT fk_pc_produto FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE CASCADE,
    CONSTRAINT fk_pc_cor     FOREIGN KEY (cor_id)     REFERENCES cor(id)     ON DELETE RESTRICT
);
CREATE INDEX ix_pc_cor ON produto_cor (cor_id);   -- filtro por cor + contagem "em uso"

-- ---- (3) Atributos botanicos escalares em `produto` (todos NULL - P12) -------------------------
ALTER TABLE produto ADD COLUMN caracteristica VARCHAR(10);
ALTER TABLE produto ADD COLUMN altura_cm      INTEGER;      -- SEMPRE em centimetros (P1/AD-SQ-80)
ALTER TABLE produto ADD COLUMN toxicidade     VARCHAR(12);  -- NULL = "nao informado" (P2)

ALTER TABLE produto ADD CONSTRAINT ck_produto_caracteristica
    CHECK (caracteristica IS NULL OR caracteristica IN ('MUDA', 'JOVEM', 'ADULTA'));
ALTER TABLE produto ADD CONSTRAINT ck_produto_toxicidade
    CHECK (toxicidade IS NULL OR toxicidade IN ('TOXICA', 'NAO_TOXICA'));
ALTER TABLE produto ADD CONSTRAINT ck_produto_altura_cm
    CHECK (altura_cm IS NULL OR (altura_cm >= 1 AND altura_cm <= 10000));
-- Regra do dono: altura so faz sentido em planta JOVEM ou ADULTA (muda nao tem porte declarado).
-- NULL-SAFE (AD-SQ-89 - correcao do dono no gate). A forma ingenua
--     CHECK (altura_cm IS NULL OR caracteristica IN ('JOVEM','ADULTA'))
-- NAO barra "altura sem caracteristica": com caracteristica = NULL e altura_cm = 30 a expressao
-- avalia FALSE OR NULL = NULL, e um CHECK so e violado quando avalia FALSE -> a linha PASSA,
-- contrariando a R13. O `caracteristica IS NOT NULL AND` fecha o buraco da logica ternaria.
ALTER TABLE produto ADD CONSTRAINT ck_produto_altura_exige_porte
    CHECK (altura_cm IS NULL
           OR (caracteristica IS NOT NULL AND caracteristica IN ('JOVEM', 'ADULTA')));

-- ---- (4) Necessidade de luz (MULTIVALORADA) ----------------------------------------------------
CREATE TABLE produto_necessidade_luz (
    produto_id BIGINT      NOT NULL,
    luz        VARCHAR(12) NOT NULL,
    CONSTRAINT pk_produto_luz  PRIMARY KEY (produto_id, luz),
    CONSTRAINT fk_pnl_produto  FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE CASCADE,
    CONSTRAINT ck_pnl_luz      CHECK (luz IN ('SOL_PLENO', 'MEIA_SOMBRA', 'SOMBRA'))
);
CREATE INDEX ix_pnl_luz ON produto_necessidade_luz (luz);

-- ---- (5) Indices dos filtros server-side (T-M6-05) ---------------------------------------------
CREATE INDEX ix_produto_caracteristica ON produto (caracteristica);
CREATE INDEX ix_produto_toxicidade     ON produto (toxicidade);
CREATE INDEX ix_produto_preco          ON produto (preco);
-- `nome` ja indexado (ix_produto_nome, V3). `estoque_atual`/`estoque_minimo` NAO ganham indice:
-- o atalho "estoque baixo" e uma comparacao entre colunas (nao sargavel) e a base e pequena.
