-- V1__baseline.sql — schema inicial M0 (Floricultura).

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120)  NOT NULL,
    email         VARCHAR(180)  NOT NULL,
    senha_hash    VARCHAR(255)  NOT NULL,
    role          VARCHAR(20)   NOT NULL DEFAULT 'USER',
    ativo         BOOLEAN       NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_role  CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE produto (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(150)  NOT NULL,
    descricao      TEXT,
    unidade_medida VARCHAR(20)   NOT NULL,               -- FC-14: escolhida no cadastro
    estoque_minimo NUMERIC(14,3) NOT NULL DEFAULT 0,     -- FC-13: configuravel
    estoque_atual  NUMERIC(14,3) NOT NULL DEFAULT 0,     -- snapshot mantido pelo servico (M2)
    imagem_url     VARCHAR(1000),                        -- FC-09: URL, nunca binario
    ativo          BOOLEAN       NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    atualizado_em  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_produto_estoque_min   CHECK (estoque_minimo >= 0),
    CONSTRAINT ck_produto_estoque_atual CHECK (estoque_atual  >= 0)
);

-- Ledger imutavel (insert-only). Sobrevive ao hard delete do produto (FC-08) via snapshot do nome.
CREATE TABLE movimentacao_estoque (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id            BIGINT,
    produto_nome          VARCHAR(150)  NOT NULL,        -- snapshot: preserva historico apos delete
    tipo                  VARCHAR(20)   NOT NULL,
    quantidade            NUMERIC(14,3) NOT NULL,
    quantidade_resultante NUMERIC(14,3) NOT NULL,
    motivo                VARCHAR(255),
    usuario_id            BIGINT,
    criado_em             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_mov_produto FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE SET NULL,
    CONSTRAINT fk_mov_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE SET NULL,
    CONSTRAINT ck_mov_tipo    CHECK (tipo IN ('ENTRADA', 'SAIDA', 'AJUSTE')),
    CONSTRAINT ck_mov_qtd     CHECK (quantidade >= 0)
);

-- Imutabilidade no nivel do banco: proibe UPDATE/DELETE em movimentacao_estoque.
CREATE OR REPLACE FUNCTION trg_movimentacao_imutavel() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'movimentacao_estoque e imutavel (insert-only): operacao % negada', TG_OP;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER movimentacao_no_update BEFORE UPDATE ON movimentacao_estoque
    FOR EACH ROW EXECUTE FUNCTION trg_movimentacao_imutavel();
CREATE TRIGGER movimentacao_no_delete BEFORE DELETE ON movimentacao_estoque
    FOR EACH ROW EXECUTE FUNCTION trg_movimentacao_imutavel();

CREATE INDEX ix_mov_produto   ON movimentacao_estoque (produto_id);
CREATE INDEX ix_mov_criado_em ON movimentacao_estoque (criado_em);

CREATE TABLE evento (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    descricao     TEXT,
    data_evento   DATE         NOT NULL,
    sazonal       BOOLEAN      NOT NULL DEFAULT FALSE,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- LGPD: tabelas de dado pessoal — SCHEMA apenas em M0, sem dados reais (AD-SQ-8). Tratamento em M4.
CREATE TABLE cliente (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    tipo_pessoa   VARCHAR(10)  NOT NULL DEFAULT 'PF',
    documento     VARCHAR(20),
    email         VARCHAR(180),
    telefone      VARCHAR(20),
    endereco      VARCHAR(255),
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_cliente_tipo CHECK (tipo_pessoa IN ('PF', 'PJ'))
);

CREATE TABLE fornecedor (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    tipo_pessoa   VARCHAR(10)  NOT NULL DEFAULT 'PJ',
    documento     VARCHAR(20),
    email         VARCHAR(180),
    telefone      VARCHAR(20),
    endereco      VARCHAR(255),
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_fornecedor_tipo CHECK (tipo_pessoa IN ('PF', 'PJ'))
);

CREATE TABLE contato (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    email         VARCHAR(180),
    telefone      VARCHAR(20),
    cargo         VARCHAR(100),
    cliente_id    BIGINT,
    fornecedor_id BIGINT,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_contato_cliente    FOREIGN KEY (cliente_id)    REFERENCES cliente(id)    ON DELETE CASCADE,
    CONSTRAINT fk_contato_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedor(id) ON DELETE CASCADE,
    CONSTRAINT ck_contato_vinculo    CHECK (cliente_id IS NOT NULL OR fornecedor_id IS NOT NULL)
);
